### ISSUE TITLE
Option for donkeys

### ISSUE THREAD

**Issue by vico93** [Aguga2201/HorseSpawn#1]
What about adding an option to spawn a (saddle/chested) donkey instead?

**Comment by Aguga2201** [comment]
Thanks for the idea. I've now implemented a simple configuration screen using owo-lib that allows you to select between horse and donkey. You can now also enable or disable the saddle and the chest.

**Comment by Aguga2201** [comment]
Thanks for the idea. I've now implemented a simple configuration screen using owo-lib that allows you to select between horse and donkey. You can now also enable or disable the saddle and the chest.
